<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_script_include">
    <sys_script_include action="INSERT_OR_UPDATE">
        <access>public</access>
        <active>true</active>
        <api_name>x_snc_datasanity.LogError</api_name>
        <caller_access>1</caller_access>
        <client_callable>false</client_callable>
        <description>Produces an error log output in the application log.</description>
        <name>LogError</name>
        <script><![CDATA[function LogError(vPayload)
{
	gs.error(x_snc_devtools.PrepareLogError(vPayload));
}]]></script>
        <sys_class_name>sys_script_include</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2024-05-15 10:14:29</sys_created_on>
        <sys_id>a6d73c3b1b86ca90063ddc61ab4bcb8d</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>LogError</sys_name>
        <sys_package display_value="DataSanity" source="x_snc_datasanity">e0746823dbad0510bcced03cd396198d</sys_package>
        <sys_policy/>
        <sys_scope display_value="DataSanity">e0746823dbad0510bcced03cd396198d</sys_scope>
        <sys_update_name>sys_script_include_a6d73c3b1b86ca90063ddc61ab4bcb8d</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2024-05-15 10:14:29</sys_updated_on>
    </sys_script_include>
</record_update>
